schemaVersion: "2.0.0"
        
commandTests:
  - name: "java exists"
    command: "java"
    args: ["-version"]
    exitCode: 0
  - name: "Working dir"
    command: "pwd"
    expectedOutput: ["/home/project"]
fileExistenceTests:
  - name: 'knowledge-share-app.jar'
    path: '/home/project/knowledge-share-app.jar'
    shouldExist: true

