apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: knowledge-share-app
    context: .
    docker: 
      buildArgs:
        SONAR_LOGIN: ""
  tagPolicy:
    gitCommit: {}
  local: {}
